# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-09 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20170209_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='avatar',
        ),
    ]
